#!/usr/bin/expect  -- 
#penghao@tencent.com
#exp_internal 1
set timeout -1 

if { [llength $argv] < 5} {
  puts "usage: $argv0 filename  dir user passwd ip "
  exit 1
}

	
	spawn	/usr/local/bin/scp  -r -P 22  [lindex $argv 2]@[lindex $argv 4]:[lindex $argv 1]/[lindex $argv 0]  ./

	expect 	{
			        "assword:" {
								send "[lindex $argv 3]\r" 
								expect eof 
								}
					 "yes/no)?" {
								send "yes\r" 		
								}
			}
